---
abstract: 'Finds audio files located on your system and maps them to L<AudioFile::Info> objects. '
author:
  - 'Markus <holli.holzer@googlemail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AudioFile-Find
no_index:
  directory:
    - t
    - inc
requires:
  AudioFile::Info: '1.09'
  File::Find::Rule: '0'
  List::MoreUtils: '0'
  Test::More: '0'
  YAML: '0'
version: '0.02'
